FROM golang:1.15.8-buster
# RUN apt-get update && apt-get install --no-install-recommends -y make=4.2.1 wget=1.20.3 curl=7.68.0 &&\
# 	apt-get clean &&\
# 	&& rm -rf /var/lib/apt/lists/* &&\
# 	wget -nv https://github.com/gohugoio/hugo/releases/download/v0.84.0/hugo_extended_0.84.0_linux-amd64.deb &&\
# 	dpkg -i hugo_extended_0.84.0_linux-amd64.deb &&\
# 	rm -f hugo_extended_0.84.0_linux-amd64.deb &&\
# 	wget -nv https://deb.nodesource.com/setup_19.x | bash - && apt-get install -y nodejs &&\
# 	npm install -g markdownlint-cli=0.34.0 &&\
# 	npm install -g markdown-link-check=3.11.2
