name: module4_task4

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Run the script
        run: |
          docker run --privileged -v $PWD:/app -w /app ubuntu:22.04 bash -c "cd module4_task4 && chmod +x setup.sh && ./setup.sh"

      - name: Markdownlint setup
        run: npm install -g markdownlint-cli
      - name: Linting
        run: cd module4_task4 && make lint
      - name: Tests
        run: cd module4_task4 && make test && make unit-tests && make integration-tests
      - name: docker
        run: cd module4_task4 && make build-docker && make docker-tests
      - name: Makefile build
        run: cd module4_task4 && make build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: building package
          path: module4_task4/awesome-website.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: 1.0.0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            module4_task4/awesome-website.zip
            module4_task4/DEPLOY.md
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "module4_task4/dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "🚀 Deployed on"
          publish-message: "🎉 Published on"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
  buildonotherversion:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' && github.ref_type == 'tag'
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Run the script
        run: cd module4_task4 && ./setup.sh
      - name: Makefile build
        run: cd module4_task4 && make build
      - name: Archive
        run: cd module4_task4 && make package
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: build package
          path: module4_task4/awesome-website.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: 1.0.0
          release_name: "1.0.0"
          files: |
            module4_task4/awesome-website.zip
            module4_task4/DEPLOY.md
